spring.application.name=school

#server.port=9898

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

avatars.directory=./avatars