server.port=8081

logging.level.ru.hogwarts.school=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

avatars.directory=./dev-avatars