spring.application.name=school

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

avatars.directory=./avatars

logging.level.ru.hogwarts.school=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n